name = "OpenAlex"
uuid = "1ebc9e4e-f4b0-4b3d-8a1b-46025f6f9b21"
authors = ["Tim Holy <tim.holy@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
